// Generated by CoffeeScript 1.3.3
var main, main2, one0, one1, unit;

main = function() {
  var ctx, cvs,
    _this = this;
  cvs = document.getElementById('canvas');
  ctx = cvs.getContext('2d');
  ctx.shadowOffsetX = 0;
  ctx.shadowOffsetY = 0;
  ctx.shadowBlur = 1;
  ctx.fillStyle = '#f00';
  (document.getElementById('run0')).onclick = function(e) {
    return main2(ctx, 0, 1);
  };
  (document.getElementById('run4')).onclick = function(e) {
    return main2(ctx, 8, 1);
  };
  return main2(ctx, 8, 1);
};

one1 = function(ctx, s, x, y) {
  var dx, dy, j, _i, _results;
  dx = s / 2;
  dy = s / 2;
  _results = [];
  for (j = _i = 0; _i <= 3; j = ++_i) {
    unit(ctx, x, y + j * dy, x + dx, y + j * dy + dy);
    unit(ctx, x + 2 * dx, y + j * dy, x + dx, y + j * dy + dy);
    unit(ctx, x + dx, y + j * dy, x, y + j * dy + dy);
    _results.push(unit(ctx, x + dx, y + j * dy, x + 2 * dx, y + j * dy + dy));
  }
  return _results;
};

main2 = function(ctx, sp, bg) {
  var i, j, n, size, _i, _j, _k, _l;
  size = 20;
  n = 20;
  ctx.clearRect(0, 0, 800, 800);
  ctx.shadowColor = '#400';
  ctx.beginPath();
  if (bg === 1) {
    for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
      for (j = _j = 1; 1 <= n ? _j <= n : _j >= n; j = 1 <= n ? ++_j : --_j) {
        ctx.fillRect(i * (size + sp) - 2, j * (size + sp) - 2, size + 4, size + 4);
      }
    }
  }
  for (i = _k = 1; 1 <= n ? _k <= n : _k >= n; i = 1 <= n ? ++_k : --_k) {
    for (j = _l = 1; 1 <= n ? _l <= n : _l >= n; j = 1 <= n ? ++_l : --_l) {
      one1(ctx, size / 2, (size + sp) * i, (size + sp) * j);
      one1(ctx, size / 2, (size + sp) * i + size / 2, (size + sp) * j);
    }
  }
  ctx.closePath();
  ctx.strokeStyle = '#fff';
  return ctx.stroke();
};

unit = function(ctx, x, y, xt, yt) {
  if ((Math.round(Math.random())) === 0) {
    ctx.moveTo(x, y);
    return ctx.lineTo(xt, yt);
  }
};

one0 = function(ctx, s, x, y) {
  var ddx, ddy, dx, dy, j, _i, _results;
  dx = s / 2;
  ddx = s / 4;
  dy = s / 2;
  ddy = s / 4;
  _results = [];
  for (j = _i = 0; _i <= 3; j = ++_i) {
    unit(ctx, x + ddx, y + j * dy, x + ddx, y + j * dy + dy);
    unit(ctx, x, y + j * dy + ddy, x + dx, y + j * dy + ddy);
    unit(ctx, x + dx + ddx, y + j * dy, x + dx + ddx, y + j * dy + dy);
    _results.push(unit(ctx, x + dx, y + j * dy + ddy, x + 2 * dx, y + j * dy + ddy));
  }
  return _results;
};

window.onload = main;
